# Prepare San Juan data

In [1]:
import scipy as sp
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import statsmodels as stats
from sklearn.preprocessing import MinMaxScaler, StandardScaler
%matplotlib inline
import myutil_prep_sj as myutil
import warnings
warnings.filterwarnings('ignore')
import sys
print(sys.executable)

/Users/carlos2/anaconda/envs/dsdht/bin/python

In [2]:
import importlib
_ = importlib.reload(myutil)

## Prepare training data

In [3]:
dfx_train = myutil.get_indexed_dataset('data/dengue_features_train.csv')
dfy_train = myutil.get_indexed_dataset('data/dengue_labels_train.csv')
dftrain = myutil.set_index(pd.merge(dfx_train, dfy_train))
_, dftrain_sj = myutil.split_dataset_by_city(dftrain)
dftrain_sj.head()

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm,total_cases
yearweekofyear,,,,,,,,,,,,,,,,,,,,,
199018,sj,1990,18,1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,...,73.365714,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0,4
199019,sj,1990,19,1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,...,77.368571,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6,5
199020,sj,1990,20,1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,...,82.052857,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4,4
199021,sj,1990,21,1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,...,80.337143,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0,3
199022,sj,1990,22,1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,...,80.460000,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8,6

In [4]:
# remove nans
dftrain_sj = myutil.set_nan_to_week_mean(dftrain_sj.copy())
dftrain_sj.isnull().sum()

city                                     0
year                                     0
weekofyear                               0
week_start_date                          0
ndvi_ne                                  0
ndvi_nw                                  0
ndvi_se                                  0
ndvi_sw                                  0
precipitation_amt_mm                     0
reanalysis_air_temp_k                    0
reanalysis_avg_temp_k                    0
reanalysis_dew_point_temp_k              0
reanalysis_max_air_temp_k                0
reanalysis_min_air_temp_k                0
reanalysis_precip_amt_kg_per_m2          0
reanalysis_relative_humidity_percent     0
reanalysis_sat_precip_amt_mm             0
reanalysis_specific_humidity_g_per_kg    0
reanalysis_tdtr_k                        0
station_avg_temp_c                       0
station_diur_temp_rng_c                  0
station_max_temp_c                       0
station_min_temp_c                       0
station_precip_mm                        0
total_cases                              0
dtype: int64

###  Add total_cases as a feature

In [5]:
dftrain_sj = myutil.add_total_cases_feature(dftrain_sj)
dftrain_sj.head()

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm,total_cases2,total_cases
yearweekofyear,,,,,,,,,,,,,,,,,,,,,
199018,sj,1990,18,1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,...,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0,4,4
199019,sj,1990,19,1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,...,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6,5,5
199020,sj,1990,20,1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,...,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4,4,4
199021,sj,1990,21,1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,...,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0,3,3
199022,sj,1990,22,1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,...,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8,6,6

###  Remove location and timescale features (since timescale is index)

In [6]:
dftrain_sj.drop(['city','year','weekofyear','week_start_date'], axis=1, inplace=True)
dftrain_sj.head()

,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,reanalysis_avg_temp_k,reanalysis_dew_point_temp_k,reanalysis_max_air_temp_k,reanalysis_min_air_temp_k,...,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm,total_cases2,total_cases
yearweekofyear,,,,,,,,,,,,,,,,,,,,,
199018,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,297.742857,292.414286,299.8,295.9,...,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0,4,4
199019,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,298.442857,293.951429,300.9,296.4,...,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6,5,5
199020,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,298.878571,295.434286,300.5,297.3,...,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4,4,4
199021,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,299.228571,295.310000,301.4,297.0,...,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0,3,3
199022,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,299.664286,295.821429,301.9,297.5,...,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8,6,6

###  Remove features with 100% correlation

In [7]:
# Features “precipitation_amount_mm” and “reanalysis_sat_precip_amt_mm” were found to be 100% correlated (pearson), 
# so we drop the latter.
# Feature“reanalysis_dew_point_temp_k” and “reanalysis_specific_humidity_g_per_kg” are 99.85% correlated (pearson), 
# so we drop the latter.
dftrain_sj.drop(['reanalysis_sat_precip_amt_mm','reanalysis_specific_humidity_g_per_kg'], axis=1, inplace=True)
dftrain_sj.head()

,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,reanalysis_avg_temp_k,reanalysis_dew_point_temp_k,reanalysis_max_air_temp_k,reanalysis_min_air_temp_k,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm,total_cases2,total_cases
yearweekofyear,,,,,,,,,,,,,,,,,,,,
199018,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,297.742857,292.414286,299.8,295.9,32.00,73.365714,2.628571,25.442857,6.900000,29.4,20.0,16.0,4,4
199019,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,298.442857,293.951429,300.9,296.4,17.94,77.368571,2.371429,26.714286,6.371429,31.7,22.2,8.6,5,5
199020,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,298.878571,295.434286,300.5,297.3,26.10,82.052857,2.300000,26.714286,6.485714,32.2,22.8,41.4,4,4
199021,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,299.228571,295.310000,301.4,297.0,13.90,80.337143,2.428571,27.471429,6.771429,33.3,23.3,4.0,3,3
199022,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,299.664286,295.821429,301.9,297.5,12.20,80.460000,3.014286,28.942857,9.371429,35.0,23.9,5.8,6,6

### Convert all temperature features to Celsius

In [8]:
dftrain_sj = myutil.convert_k_to_celsius(dftrain_sj.copy())
dftrain_sj.head()

,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,reanalysis_avg_temp_k,reanalysis_dew_point_temp_k,reanalysis_max_air_temp_k,reanalysis_min_air_temp_k,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm,total_cases2,total_cases
yearweekofyear,,,,,,,,,,,,,,,,,,,,
199018,0.122600,0.103725,0.198483,0.177617,12.42,24.422857,24.592857,19.264286,26.65,22.75,32.00,73.365714,2.628571,25.442857,6.900000,29.4,20.0,16.0,4,4
199019,0.169900,0.142175,0.162357,0.155486,22.82,25.061429,25.292857,20.801429,27.75,23.25,17.94,77.368571,2.371429,26.714286,6.371429,31.7,22.2,8.6,5,5
199020,0.032250,0.172967,0.157200,0.170843,34.54,25.631429,25.728571,22.284286,27.35,24.15,26.10,82.052857,2.300000,26.714286,6.485714,32.2,22.8,41.4,4,4
199021,0.128633,0.245067,0.227557,0.235886,15.36,25.837143,26.078571,22.160000,28.25,23.85,13.90,80.337143,2.428571,27.471429,6.771429,33.3,23.3,4.0,3,3
199022,0.196200,0.262200,0.251200,0.247340,7.52,26.368571,26.514286,22.671429,28.75,24.35,12.20,80.460000,3.014286,28.942857,9.371429,35.0,23.9,5.8,6,6

## Save training data

In [9]:
dftrain_sj.iloc[:,:-1].to_csv('data/dengue_features_train_with_outliers_sj.csv')
dftrain_sj.iloc[:,-1:].to_csv('data/dengue_labels_train_sj.csv')

======================================================================================================================

## Prepare test data

In [10]:
dfx_test = myutil.get_indexed_dataset('data/dengue_features_test.csv')
dfx_test = dfx_test[dfx_test['city']=='sj']
dfx_test.head()

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
yearweekofyear,,,,,,,,,,,,,,,,,,,,,
200818,sj,2008,18,2008-04-29,-0.0189,-0.018900,0.102729,0.091200,78.60,298.492857,...,25.37,78.781429,78.60,15.918571,3.128571,26.528571,7.057143,33.3,21.7,75.2
200819,sj,2008,19,2008-05-06,-0.0180,-0.012400,0.082043,0.072314,12.56,298.475714,...,21.83,78.230000,12.56,15.791429,2.571429,26.071429,5.557143,30.0,22.2,34.3
200820,sj,2008,20,2008-05-13,-0.0015,NaN,0.151083,0.091529,3.66,299.455714,...,4.12,78.270000,3.66,16.674286,4.428571,27.928571,7.785714,32.8,22.8,3.0
200821,sj,2008,21,2008-05-20,NaN,-0.019867,0.124329,0.125686,0.00,299.690000,...,2.20,73.015714,0.00,15.775714,4.342857,28.057143,6.271429,33.3,24.4,0.3
200822,sj,2008,22,2008-05-27,0.0568,0.039833,0.062267,0.075914,0.76,299.780000,...,4.36,74.084286,0.76,16.137143,3.542857,27.614286,7.085714,33.3,23.3,84.1

In [11]:
# remove nans
dftest_sj = myutil.set_nan_to_week_mean(dfx_test.copy())
dftest_sj.isnull().sum()

city                                     0
year                                     0
weekofyear                               0
week_start_date                          0
ndvi_ne                                  0
ndvi_nw                                  0
ndvi_se                                  0
ndvi_sw                                  0
precipitation_amt_mm                     0
reanalysis_air_temp_k                    0
reanalysis_avg_temp_k                    0
reanalysis_dew_point_temp_k              0
reanalysis_max_air_temp_k                0
reanalysis_min_air_temp_k                0
reanalysis_precip_amt_kg_per_m2          0
reanalysis_relative_humidity_percent     0
reanalysis_sat_precip_amt_mm             0
reanalysis_specific_humidity_g_per_kg    0
reanalysis_tdtr_k                        0
station_avg_temp_c                       0
station_diur_temp_rng_c                  0
station_max_temp_c                       0
station_min_temp_c                       0
station_precip_mm                        0
dtype: int64

###  Remove location and timescale features (since timescale is index)

In [12]:
dftest_sj.drop(['city','year','weekofyear','week_start_date'], axis=1, inplace=True)
dftest_sj.head()

,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,reanalysis_avg_temp_k,reanalysis_dew_point_temp_k,reanalysis_max_air_temp_k,reanalysis_min_air_temp_k,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
yearweekofyear,,,,,,,,,,,,,,,,,,,,
200818,-0.018900,-0.018900,0.102729,0.091200,78.60,298.492857,298.550000,294.527143,301.1,296.4,25.37,78.781429,78.60,15.918571,3.128571,26.528571,7.057143,33.3,21.7,75.2
200819,-0.018000,-0.012400,0.082043,0.072314,12.56,298.475714,298.557143,294.395714,300.8,296.7,21.83,78.230000,12.56,15.791429,2.571429,26.071429,5.557143,30.0,22.2,34.3
200820,-0.001500,0.051510,0.151083,0.091529,3.66,299.455714,299.357143,295.308571,302.2,296.4,4.12,78.270000,3.66,16.674286,4.428571,27.928571,7.785714,32.8,22.8,3.0
200821,0.108304,-0.019867,0.124329,0.125686,0.00,299.690000,299.728571,294.402857,303.0,296.9,2.20,73.015714,0.00,15.775714,4.342857,28.057143,6.271429,33.3,24.4,0.3
200822,0.056800,0.039833,0.062267,0.075914,0.76,299.780000,299.671429,294.760000,302.3,297.3,4.36,74.084286,0.76,16.137143,3.542857,27.614286,7.085714,33.3,23.3,84.1

###  Remove features with 100% correlation

In [13]:
# Features “precipitation_amount_mm” and “reanalysis_sat_precip_amt_mm” were found to be 100% correlated (pearson), 
# so we drop the latter.
# Feature“reanalysis_dew_point_temp_k” and “reanalysis_specific_humidity_g_per_kg” are 99.85% correlated (pearson), 
# so we drop the latter.
dftest_sj.drop(['reanalysis_sat_precip_amt_mm','reanalysis_specific_humidity_g_per_kg'], axis=1, inplace=True)
dftest_sj.head()

,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,reanalysis_avg_temp_k,reanalysis_dew_point_temp_k,reanalysis_max_air_temp_k,reanalysis_min_air_temp_k,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
yearweekofyear,,,,,,,,,,,,,,,,,,
200818,-0.018900,-0.018900,0.102729,0.091200,78.60,298.492857,298.550000,294.527143,301.1,296.4,25.37,78.781429,3.128571,26.528571,7.057143,33.3,21.7,75.2
200819,-0.018000,-0.012400,0.082043,0.072314,12.56,298.475714,298.557143,294.395714,300.8,296.7,21.83,78.230000,2.571429,26.071429,5.557143,30.0,22.2,34.3
200820,-0.001500,0.051510,0.151083,0.091529,3.66,299.455714,299.357143,295.308571,302.2,296.4,4.12,78.270000,4.428571,27.928571,7.785714,32.8,22.8,3.0
200821,0.108304,-0.019867,0.124329,0.125686,0.00,299.690000,299.728571,294.402857,303.0,296.9,2.20,73.015714,4.342857,28.057143,6.271429,33.3,24.4,0.3
200822,0.056800,0.039833,0.062267,0.075914,0.76,299.780000,299.671429,294.760000,302.3,297.3,4.36,74.084286,3.542857,27.614286,7.085714,33.3,23.3,84.1

### Convert all temperature features to Celsius

In [14]:
dftest_sj = myutil.convert_k_to_celsius(dftest_sj.copy())
dftest_sj.head()

,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,reanalysis_avg_temp_k,reanalysis_dew_point_temp_k,reanalysis_max_air_temp_k,reanalysis_min_air_temp_k,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
yearweekofyear,,,,,,,,,,,,,,,,,,
200818,-0.018900,-0.018900,0.102729,0.091200,78.60,25.342857,25.400000,21.377143,27.95,23.25,25.37,78.781429,3.128571,26.528571,7.057143,33.3,21.7,75.2
200819,-0.018000,-0.012400,0.082043,0.072314,12.56,25.325714,25.407143,21.245714,27.65,23.55,21.83,78.230000,2.571429,26.071429,5.557143,30.0,22.2,34.3
200820,-0.001500,0.051510,0.151083,0.091529,3.66,26.305714,26.207143,22.158571,29.05,23.25,4.12,78.270000,4.428571,27.928571,7.785714,32.8,22.8,3.0
200821,0.108304,-0.019867,0.124329,0.125686,0.00,26.540000,26.578571,21.252857,29.85,23.75,2.20,73.015714,4.342857,28.057143,6.271429,33.3,24.4,0.3
200822,0.056800,0.039833,0.062267,0.075914,0.76,26.630000,26.521429,21.610000,29.15,24.15,4.36,74.084286,3.542857,27.614286,7.085714,33.3,23.3,84.1

## Save test data

In [15]:
dftest_sj.to_csv('data/dengue_features_test_with_outliers_sj.csv')

In [16]:
dftest_sj.index.size

260